### ISSUE TITLE
 BUG: Download Thread Images Stall

### ISSUE THREAD

**Issue by Tasuba** [grzegorznittner/chanu#430]
Thread image downloading notifications and process are stalled and stopped sometimes.
Exact cause is unknown and causes any queued image downloads to never start.

**Comment by Datastreamx** [comment]
Problem still persist at 2.0.12

**Comment by johnarleyburns** [comment]
sorry can't reproduce

**Comment by Datastreamx** [comment]
It usually happens on threads that I've been watching for a long time and have been pulling from a lot. (at least a week)

**Comment by Junohea** [comment]
A bit more testing is required but I find it typically happens if I try to use it in a thread where an image has been removed by a mod/janitor

**Comment by Datastreamx** [comment]
I found this out too like 2 weeks ago. Just neglected to mention it because I'd remember it when I'd use the app and that is right before bed. But that is indeed the cause.

**Comment by johnarleyburns** [comment]
Uh, if the thread has been removed, the images are toast and can't be
downloaded anymore, unfortunately.

**Comment by Junohea** [comment]
Ah let me clarify, the issue that I've seen is that if an image has been removed in this manner (but the thread is still otherwise available) chanu will stall when using the "download images" function because it'll try to download a file that isn't there, and rather than continuing down the thread it comes to a stop. I've not yet looked at the code otherwise I could try to pinpoint the spot where it occurs

**Comment by johnarleyburns** [comment]
We will have a fix out shortly.
