### ISSUE TITLE
Slow Board Loading

### ISSUE THREAD

**Issue by yate** [grzegorznittner/chanu#436]
The first time a board is loaded it is pretty slow. What I've found is that BoardActivity and other classes are calling refresh() and onRefresh() multiple times, something like 4 or 5.  I'm having trouble figuring out which ones are necessary and which ones can be removed, if any.  

Any ideas?  I'll continue to experiment around.

**Comment by johnarleyburns** [comment]
I think just comment them out and then see what happens.  The refresh() and
onRefresh() method should be combined I think.  It worked fine when it was
"fully manual", I think I screwed it up when I tried to make it
automatically refresh.  So in short, the problem is all with the
auto-refresh calculations, it's screwed up.

**Comment by yate** [comment]
I got rid of one call and things seems to be working okay.  A couple questions:

Do you know where the automatic refresh job is set up in the code?
Where are the dark icons for the "View Options" list.  They are white using the dark theme in Lollipop and I'm struggling to find out where they are.

**Comment by johnarleyburns** [comment]
1. Auto Refresh Code

Are you talking about thread refresh or board refresh?  These are two
different things.  Thread Refresh is in ThreadFragment.java:

 protected final Runnable autoUpdateRunnable = new Runnable() {
        @Override
        public void run() {
            if (DEBUG) Log.i(TAG, "autoUpdateRunnable preparing refresh /"
- boardCode + "/" + threadNo);
          if (NetworkProfileManager.instance().getActivityId() !=
  getChanActivityId()) {
              if (DEBUG) Log.i(TAG, "autoUpdateRunnable no longer
  foreground, cancelling update /" + boardCode + "/" + threadNo);
              return;
          }
          if (handler == null) {
              if (DEBUG) Log.i(TAG, "autoUpdateRunnable null handler,
  cancelling update /" + boardCode + "/" + threadNo);
              return;
          }
          if (DEBUG) Log.i(TAG, "autoUpdateRunnable manually refreshing
  /" + boardCode + "/" + threadNo);
          manualRefresh();
          if (DEBUG) Log.i(TAG, "autoUpdateRunnable scheduling next auto
  refresh /" + boardCode + "/" + threadNo);
          scheduleAutoUpdate();
      }
  };

It's scheduled to run in method "scheduleAutoUpdate()" which is called in
onStart().
1. View Options Icon

So the View Options icons are copied directly from the
"android-design-resources" folder:

android-design-resources\Icons\All_Icons\holo_light\xhdpi\4_collections_view_as_grid.png

They are renamed "collections_view_as_grid.png" because android doesn't
allow icons to start with a number.

I think I just forgot to include the dark icons, so what you can do is copy
the same 4_collections_view_as_grid.png for each size from the android
design resources "holo_dark" folder for each screen density, and update the
code to use them for the dark theme.  This means you have to "themize" the
pref_view_options icon in thread_menu.xml and board_menu.xml.  If you have
trouble let me know.
1. BTW I issued the new release yesterday and f-droid still didn't pick it
   up, I'm not sure if they're just being really slow or if we did something
   wrong.

**Comment by yate** [comment]
Thanks!  F-droid is slow because they have to manually add the new metadata  :(.  But our new release was detected and it should be added soon.  You can see it on the [apps to update page](https://f-droid.org/wiki/page/Category:Apps_to_Update) and under the [version section](https://f-droid.org/wiki/page/com.chanapps.four.activity)

**Comment by yate** [comment]
Darn the captcha fix isn't working anymore

**Comment by johnarleyburns** [comment]
2.0.6 works for me

**Comment by yate** [comment]
Really, maybe in just horrible at entering captchas but I still can't post
on /g/ :o.

**Comment by johnarleyburns** [comment]
was testing on /b/, doesnt work anywhere else

**Comment by yate** [comment]
Sad
:(.  I'll be able to look later tonight

**Comment by yate** [comment]
The captcha is working but only for two word ones it seems. I probably screwed up the input somewhere

**Comment by yate** [comment]
Actually probably because  its doubling the input even if it's supposed to be one.

```
    public String getRecaptchaResponse() {
        String t = recaptchaText.getText().toString();
        if (t.indexOf(" ") == -1) // autodoubling for quick entry
        t = t + " " + t;
        return t;
    }
```

**Comment by johnarleyburns** [comment]
it should only do this when you have two for the source, it makes it so you
dont have to enter both

**Comment by yate** [comment]
by source do you mean the actual captcha image, or the text that they write?

**Comment by johnarleyburns** [comment]
it used to be you always had to write two words, but if you just wrote the
captcha one i would copy it and it would work.

just comment that out if its breaking things

**Comment by yate** [comment]
Okay yeah they must have changed it because I just got a one word captcha.  When i entered it gave me "invalid captcha" but the next one was two words and it worked.  I'll try commenting it out later when I get home

**Comment by johnarleyburns** [comment]
yeah im not getting any captchas to work in 2.0.7
