### ISSUE TITLE
Thumbnail Problem

### ISSUE THREAD

**Issue by FluxMaster** [grzegorznittner/chanu#453]
Thumbnails don't load in Catalog view or Gallery view.

**Comment by tyrionone** [comment]
Same problem here, using Oneplus One on CM12.1.
since yesterday. day before there were NO problems at all
what i already tried:
- deleted data
- empty cache
- set NSFW to ON :-)

> problem still excists

**Comment by johnarleyburns** [comment]
Yes not sure how to fix, as my ISP is currently blocking 4chan.

**Comment by tyrionone** [comment]
Ok.  Good luck in a quick solve

Sent from my Cyanogen phone

Op 29 okt. 2015 15:30 schreef John Burns notifications@github.com:
Yes not sure how to fix, as my ISP is currently blocking 4chan.

**Comment by yate** [comment]
I can probably look into this today

**Comment by johnarleyburns** [comment]
Thanks, my ISP blocked 4chan (but not reddit, those bastards!), so I can't
really test it from my computer.  From the reports I've been getting,
everything works except images and thumbnails.  Not sure why it just died,
I checked the 4chan.org api but didn't see any changes.

**Comment by tyrionone** [comment]
Funny thing is ;
/h 1st one works
/hc 1st 2 work
/hm 1st works....

Strang

Good luck my friend

Sent from my CyanogenMod phone

Op 29 okt. 2015 9:03 PM schreef John Burns notifications@github.com:
Thanks, my ISP blocked 4chan (but not reddit, those bastards!), so I can't
really test it from my computer. From the reports I've been getting,
everything works except images and thumbnails. Not sure why it just died,
I checked the 4chan.org api but didn't see any changes.

**Comment by johnarleyburns** [comment]
fix 2.0.15 will be on f-droid in a few days, or if you can't wait install:
https://github.com/grzegorznittner/chanu/releases/download/v2.0.15/4channer-debug.apk

**Comment by tyrionone** [comment]
Good morning John.
Tried to install apk. Didn't work due to?
Pic related

Sent from my CyanogenMod phone

Op 30 okt. 2015 4:19 AM schreef John Burns notifications@github.com:
fix 2.0.15 will be on f-droid in a few days, or if you can't wait install:
https://github.com/grzegorznittner/chanu/releases/download/v2.0.15/4channer-debug.apk

**Comment by tyrionone** [comment]
John,

Deinstalled. 14
Installed 15
Seems to work
You are Awesome
Big thank you

Sent from my CyanogenMod phone

Op 30 okt. 2015 7:05 AM schreef lovly_1@hotmail.com:

Good morning John.
Tried to install apk. Didn't work due to?
Pic related

Sent from my CyanogenMod phone

Op 30 okt. 2015 4:19 AM schreef John Burns notifications@github.com:
fix 2.0.15 will be on f-droid in a few days, or if you can't wait install:
https://github.com/grzegorznittner/chanu/releases/download/v2.0.15/4channer-debug.apk

**Comment by FluxMaster** [comment]
Thanks for getting to my issue so quickly. One of these days I'll start studying the code so I can return the favor.

**Comment by johnarleyburns** [comment]
Well the main thing now, just a minor change, is to add the new boards,
that would be a good place to start.

Also if someone could put it back up on google play would be good, it was
banned so I can't put it back up myself.

**Comment by Greznor** [comment]
I have the project ported to an Android Studio project. I'll be happy to contribute it to a new branch and add the new boards too.

**Comment by johnarleyburns** [comment]
Awesome!  Just submit a merge request when you're ready, and then I'll
create a new release from it.
