### ISSUE TITLE
Deleting app cache also deletes widget peferences

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#79]
After deleting cache folder i got all my widgets set with default board.
In logs I see:
E/UpdateWidgetService(2874): Null board code found for widget=4 defaulting to /a
E/UpdateWidgetService(2874): Null board code found for widget=8 defaulting to /a
E/UpdateWidgetService(2874): Null board code found for widget=9 defaulting to /a

**Comment by johnarleyburns** [comment]
Unfortunately there's nothing we can do about this as the cache directory
stores the preferences file which is where the config comes from.

What we _could_ do is make the cache under a subdirectory (like
cache/boards) instead of the top-level cache directory, and then only clear
that, so that the preferences remain.

This is also a problem with the "reset preferences" button, I think I put
in a guard to add back the widget prefs after removing everything else.

The root of the issue is that Android doesn't allow programmatic removal of
widgets, only the user can do it and it must be done manually.  That's why
I put the guard around the "reset preferences" link, you could try the same
thing for cache as well and that should fix it.

On Mon, Jan 21, 2013 at 11:09 PM, Grzegorz Nittner <notifications@github.com

**Comment by grzegorznittner** [comment]
I deleted cache from android system.
We can try displaying "please configure" images which will open widget
configure popup after tapping on the widget.
